function getRandomGreeting() {
  var greetings = [
    "Did you know children are annoying?",
    "Did you know, you are brainroted?",
    "How many sides does a circle have?",
    "WOW you can read!!!!",
    "Made you look!",
    "Redbull gives you wings...",
    "Since November 2024",
    "As seen on TV!",
    "doot doot",
    "uhmmmmm",
    ":D",
    "Edited by AMD, credits to 3kh0",
    "Reload the page NOW!",
    "Gyatt",
    "Running virus.exe",
    "WARNING: You may lose braincells as you proceed.",
    "You still here?",
    "#Relatable",
    "Fortnite is cringe",
    "Powered by mummies",
    "Brawl Stars is also cringe",
    "Got to go.",
    "Just a teen",
    "Sponsered by Lunchly!",
    "Sponsored by Prime",
    "KSI",
    "Im in the thick of it",
    "AMD is a bozo",
    "From the screen to the ring!!!",
    "PJ sandwiches are overrated",
    "Your still reloading?",
    "You're a real jerk!",
    "w h a t",
    "Honorable mension to Jojo Siwa",
    "what the sigma",
    "200 pumps back",
    "Shoutout to your mom!",
    "Chicken butt",
    "Are you serious?",
    "It is time to get freaky",
    "What the skibidi",
    "Don't ask questions if you can't handle the answers",
    "If you are using Microsoft Edge, your a dinosaur.",
    "Skibidi",
    "Shoutout to nateprox",
    "Go Blues!!",
    "youtube.com/watch?v=dQw4w9WgXcQ",
    "https://m.facebook.com/thetypicalmom"
    "Please stop posting furry images.",
    "Never back down never what?",
    "POV that one person who's 2 braincells are fighting for second place.",
    "Ding Dong eat it up...",
    "No furries allowed",
    "Your toes will be touched tonight",
    "'If you are trash go play Fortnite you loser",
    "Im not a furry I swear",
    "i wanted free vbucks :(",
    "SALSA VERDE",
    "reload for another message",
    "Stop being a discord mod",
    "He stomped on his fruit loops and became a cereal killer.",
    "And just to think I knew him before he was famous",
    "It is friday bro",
    "That proves you are unusual",
    "Im tweaking bro",
    "Bruh",
    "Cringe",
    "NUKE INCOMING!",
    "I spent too much time making these",
    "Over 70 of these..."
    "Sup"
    "Wussup"
    "What's poppin"
  ];
  var randomIndex = Math.floor(Math.random() * greetings.length);
  return greetings[randomIndex];
}

document.getElementById("subtitle").innerText = getRandomGreeting();
